### ISSUE TITLE
[Request] temperature in Mode

### ISSUE THREAD

**Issue by varadujagan** [piitaya/lovelace-climate-mode-entity-row#5]
in climate, if there is an option to set the temperature. that will be very nice 
for example 

```
    modes:
      - icon: "mdi:brightness-auto"
        hvac_mode: "heat"
        fan_mode: "on_high"
        temperature: "24"            <--- like this 
        swing_mode: "auto"
        color: "#34c6eb"

```
